version: '3'
services:
#    zookeeper:
#        image: confluentinc/cp-zookeeper
#        environment:
#            ZOOKEEPER_CLIENT_PORT: 2181
#            ZOOKEEPER_TICK_TIME: 2000
#        volumes:
#            - zk-data:/var/lib/zookeeper/data
#            - zk-logs:/var/lib/zookeeper/log
#            - secrets:/etc/zookeeper/secrets
#        restart: unless-stopped
#
#    kafka:
#        image: confluentinc/cp-kafka
#        depends_on:
#            - zookeeper
#        ports:
#            - "9092:9092"
#            - "9093:9093"
#        environment:
#            KAFKA_BROKER_ID: 1
#            KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
#            KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:9092,OUTSIDE://157.230.32.117:9093
#            KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
#            KAFKA_LISTENERS: INSIDE://0.0.0.0:9092,OUTSIDE://0.0.0.0:9093
#            KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
#            KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
#        volumes:
#            - kafka-data:/var/lib/kafka/data
#            - secrets:/etc/kafka/secrets
#        restart: unless-stopped

    web:
        build: test-server/
        ports:
            - "5000:5000"

#volumes:
#    es-volume:
#    zk-logs: {}
#    zk-data: {}
#    kafka-data: {}
#    secrets: {}